config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  delete 'logout' => 'sessions#destory'
  resources :users
  resources :sessions, only: [:new, :create]

end

app/models/channel.rb
class Channel < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

	has_many :subscriptions
	has_many :channels, through: :subscriptions

	validates_presence_of :email, :hashed_password
	validate :password_requirements

	def password
		@password ||= BCrypt::Password.new(hashed_password)
	end

	def password=(new_password)
		@raw_password = new_password
		@password = BCrypt::Password.create(new_password)
		self.hashed_password = @password
	end

	def self.authenticate(email, password)
		@user = User.find_by_email(email)
		@user if @user && @user.password == password
	end

private
	def raw_password
    @raw_password
  end
  def password_requirements
    # only run validations if raw_password is set (not nil)
    # OR if the record hasn't been saved yet (we require a
    # password to create a user)
    if raw_password || new_record?
      # validate that the raw password is at least 6 characters long
      # and contains 1 special character (!@#$%^&*)
      if raw_password.length < 6 || !(raw_password =~ /[!@#$%^&*]/)
        errors.add(:password, "must be at least 6 characters long and contain at least 1 special character (!@#$%^&*).")
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	include UsersHelper
	def index
		@user = current_user if session[:user_id]
		# redirect_to @user if @user
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.find_by(email: user_params[:email])
		if @user and User.authenticate(@user.email, user_params[:password])
			session[:user_id] = @user.id
			redirect_to :root
		else
			flash[:error] = "Oops, something went wrong!"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to :root
	end

	private

	def user_params
		params.require(:user).permit(:email, :password)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end
	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		if @user.valid?
			session[:user_id] = @user.id
			redirect_to :root
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@subscriptions = @user.subscriptions
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes!(user_params)
		redirect_to @user
	end

	def destroy
		User.find(params[:id]).destroy
		redirect_to login_url
	end

	private

	def user_params
		params.require(:user).permit(:email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		User.find(session[:user_id])
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yalp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 	<% flash.each do |key, value| %>
  	<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<%= flash[:error] %>

<p>
<%= link_to 'Sign In', new_session_path %><br><br>
<%= link_to 'Sign Up', new_user_path %> 
</p>

app/views/users/index.html.erb
index.html.erb

app/views/users/new.html.erb
<% if @user && @user.errors.any? %>

  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

<% end %>

<%= form_for(:user, url: users_path) do |f| %>
  <%= label_tag("Email") %><br>
  <input type="text" name="user[email]"></input><br><br>

  <%= label_tag("Password") %><br>
  <input type="password" name="user[password]"></input><br><br>
  <%= submit_tag("Sign up") %>
<% end %>

app/views/users/show.html.erb
Test